<html>
<body>
<%=request.getSession().getAttribute("aa")%>
<%=request.getAttribute("bb")%>
<%=request.getSession().getId()%>
<%=pageContext.getAttribute("cc")%>
<%=application.getAttribute("dd")%>
</body>
</html>